[background]
# Path to the background image
path = "/etc/greetd/background.jpg"
fit = "Cover"

[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "Adwaita"

# Font name and size
font_name = "Roboto Mono"

# Icon theme name
icon_theme_name = "Qogir-Dark"

# GTK theme name
theme_name = "Nordic"

[commands]
reboot = ["systemctl", "reboot"]
poweroff = ["systemctl", "poweroff"]

[appearance]
# The message that initially displays on startup
greeting_msg = "Lite-Desk"
